{
 "title": "Main dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "tp-arquitectura7573-2023-node-1, tp-arquitectura7573-2023-node-2, tp-arquitectura7573-2023-node-3, tp-arquitectura7573-2023-cadvisor-1, tp-arquitectura7573-2023-grafana-1, tp-arquitectura7573-2023-graphite-1,  tp-arquitectura7573-2023-nginx-1, tp-arquitectura7573-2023-bbox-1"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests State (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Ok')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Connection Errors')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'O')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Too Many Requests')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.403, 'Forbidden')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.500, 'Internal Error')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.504, 'Gateway Timeout')"
    }
   ]
  },
  {
   "title": "Response Time (Client Side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Response Time (Services)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.hot-shots-api.service.metars.response_time, 'Metars')"
    },
    {
     "target": "alias(stats.gauges.hot-shots-api.service.spaceflight-news.response_time, 'Spaceflight')"
    },
    {
     "target": "alias(stats.gauges.hot-shots-api.service.quotes.response_time, 'Quotes')"
    }
   ]
  },
  {
   "title": "Response Time (External Services)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.hot-shots-api.external-service.metars.response_time, 'Metars')"
    },
    {
     "target": "alias(stats.gauges.hot-shots-api.external-service.spaceflight-news.response_time, 'Spaceflight')"
    },
    {
     "target": "alias(stats.gauges.hot-shots-api.external-service.quotes.response_time, 'Quotes')"
    }
   ]
  },
  {
   "title": "Resources Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 34359738368), 'Memory')"
    }
   ]
  }
 ]
}